### ISSUE TITLE
An error at start. 

### ISSUE THREAD

**Issue by tionebDotsamapha** [dps/rpi-timelapse#4]
I have this error when I launch the program. 

pi@raspberrypi:~/rpi-timelapse $ python tl.py
Timelapse
Traceback (most recent call last):
  File "tl.py", line 124, in <module>
    main()
  File "tl.py", line 75, in main
    ui = TimelapseUi()
  File "/home/pi/rpi-timelapse/ui.py", line 62, in __init__
    self._lcd.backlight(self._lcd.ON)
AttributeError: 'Adafruit_CharLCDPlate' object has no attribute 'backlight'

Have you an issue? Please.

**Comment by BenSta13** [comment]
Hi,

I think those errors come from the LCDisplay that was originally intended for this project. As I also don't have one (like this) I had errors too (can't remember the specifics). 

What I found was alanzchen's fork of this git (**https://github.com/alanzchen/rpi-timelapse**) that works without the display. I use it for my project and it works for me. Give it a try.

Cool name by the way ;D

=)

**Comment by BenSta13** [comment]
ah, and don't use my fork. I haven't updated it yet (because I wanted to fork of alenzchen's fork but haven't found out how to 'unfork' from the original one yet).
